SC-Front-End/Nike-Clone

package-lock.json, src/pages/ProductList.js
=> test : push확인

package-lock.json, package.json, src/App.js, src/data/ProductDetailData.js, src/pages/Product.jsx
feat: 상품 상세페이지 반응형 구현 (사진카드 제외)
=> feat: 상품 상세페이지 반응형 구현 (사진카드 제외)

package-lock.json, src/App.js, src/components/MainPage/Header.js
=> feat: header 구현 완성

src/App.js, src/components/MainPage/NavFooer.js
=> navfoorer 구현 완료

package-lock.json, package.json
=> chore: 필요한 라이브러리 설치

src/App.js, src/components/MainPage/Gift.js
=> feat: gift 구현 완료

src/App.js, src/components/MainPage/Apparel.js
=> feat: 연말 선물 추천 apparel 구현 완성

src/App.js, src/components/MainPage/Apparel.js, src/components/MainPage/VictoryF.js
feat: Victory 두번째 메인 section 구현 완료
=> feat: Victory 두번째 메인 section 구현 완료

src/App.js, src/components/MainPage/LastContainer.js
=> feat: LastContainer 구현 완성

src/App.js, src/components/MainPage/Ad.js
=> feat: 나이키 어플 소개 구현 완성

src/App.js, src/components/MainPage/Footer.js, src/components/MainPage/Share.js
share 라이브러리 설치 및 컴포넌트 생성, footer 구현 완성
=> share 라이브러리 설치 및 컴포넌트 생성, footer 구현 완성

package-lock.json, src/components/MainPage/Nav.js
=> feat: nav 검색창 기능 구현 완료

src/components/MainPage/Header.js
=> feat: 고객센터 모달 기능 구현 완성

src/components/MainPage/Footer.js
=> footer css 수정

src/components/ProductDetail/Product.jsx
feat: 반응형, Header, Nav, Footer 합침
=> feat: 반응형, Header, Nav, Footer 합침

src/App.js, src/components/EventPage/EventMainPage.js, src/components/ProductDetail/Product.jsx
=> 이벤트페이지, 상품 디테일 페이지 연결 완료

src/App.js, src/components/LoginPage/Login.jsx, src/components/MainPage/Header.jsx, src/components/MainPage/MainPageC.jsx
=> 로그인 페이지 연결

src/components/MainPage/LastContainer.jsx, src/components/MainPage/MainContainer.jsx, src/components/MainPage/Nav.jsx, src/components/MainPage/VictoryF.jsx, src/components/productList/Products.jsx
=> style: 메인페이지 css 수정

src/App.js, src/components/MainPage/Nav.jsx
=> style: nav css 수정 완료

src/App.js, src/components/LoginPage/Login.jsx, src/components/MainPage/Nav.jsx, src/components/productList/Products.jsx
=> feat: product 페이지 연결 작업중

.gitignore, netlify.toml, public/index.html, src/components/MainPage/Header.jsx
=> style: 최종 css 수정완료

public/index.html
chore: main page typo is corrected
=> chore: main page typo is corrected

public/index.html
chore: typo in the index file is deleted
=> chore: typo in the index file is deleted

src/App.js, src/components/ProductDetail/InfoSection.jsx, src/components/ProductDetail/Product.jsx, src/components/ProductDetail/SizeInput.jsx, src/data/ProductDetailData.js
feat: infoSection, SizeInput 모듈화
=> feat: infoSection, SizeInput 모듈화
